#!/usr/bin/env python3
import argparse
import sys
import time
import uuid
from pathlib import Path

from connection_security import (
    load_public_key,
    remove_connection_file_if_unchanged,
    write_encrypted_connection_file,
)
from consumer_output import create_consumer_output
from network_access import (
    accept_from_allowed_network,
    create_tcp_listener,
    ipv4_network,
    tcp_port_range,
)
from single_socket_io import PROTOCOL_VERSION, VARIABLES
from socket_protocol import (
    receive_hello,
    receive_message,
    send_ack,
    verify_producer_private_key,
)
from timing_log import TimingLog, timestamp


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Receive all mockProducer arrays over one TCP connection."
    )
    parser.add_argument("connection_file", help="rendezvous file to create")
    parser.add_argument("output", help="ADIOS output, or pickle output fallback")
    parser.add_argument(
        "--public-key",
        required=True,
        help="Curve25519 public key generated by keygen.py (required)",
    )
    parser.add_argument(
        "--allow-ip-range",
        action="append",
        required=True,
        type=ipv4_network,
        help="allowed producer IPv4 CIDR; may be specified more than once",
    )
    parser.add_argument(
        "--engine",
        default="BP5",
        help="ADIOS engine (default: BP5)",
    )
    parser.add_argument(
        "--bind-host",
        default="127.0.0.1",
        help="interface on which to listen (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--port",
        type=tcp_port_range,
        metavar="PORT[-END]",
        help=(
            "preferred listening port or bounded port range; a single occupied "
            "port increments through 65535 (default: any available port)"
        ),
    )
    parser.add_argument(
        "--advertise-host",
        help="host name written to the file (default: bind host)",
    )
    parser.add_argument(
        "--timing-log",
        default="mockConsumerSingleSocket.log",
        help="timing log file (default: mockConsumerSingleSocket.log)",
    )
    parser.add_argument(
        "--append-output",
        action="store_true",
        help="append steps to an output created by an earlier consumer",
    )
    return parser.parse_args(argv)


def create_listener(bind_host, ports=None):
    return create_tcp_listener(bind_host, ports, backlog=1)


def write_connection_file(path, advertise_host, listener, session_id, public_key):
    connection_info = {
        "id": "singlesocket",
        "protocol_version": PROTOCOL_VERSION,
        "consumer_id": session_id,
        "host": advertise_host,
        "port": listener.getsockname()[1],
    }
    return write_encrypted_connection_file(path, connection_info, public_key)


def remove_own_connection_file(path, expected_contents):
    remove_connection_file_if_unchanged(path, expected_contents)


def accept_connection(listener, session_id, public_key, allowed_networks):
    connection, address = accept_from_allowed_network(listener, allowed_networks)
    try:
        verify_producer_private_key(connection, public_key)
        variables, requested_consumer_id = receive_hello(connection)
        if requested_consumer_id != session_id:
            raise RuntimeError("Producer used stale socket connection information")
        if variables != VARIABLES:
            raise RuntimeError(
                f"Expected variables {list(VARIABLES)}, received {list(variables)}"
            )
    except Exception:
        connection.close()
        raise
    print(
        f"Connected all variables from {address[0]}:{address[1]}",
        flush=True,
    )
    return connection


def receive_steps(
    connection,
    output,
    engine,
    timing_log,
    before_receive=None,
    append_output=False,
):
    io = None
    step = 0
    try:
        while True:
            if before_receive is not None:
                before_receive(step)
            receive_started_at = timestamp()
            receive_start = time.perf_counter()
            variables = receive_message(connection)
            receive_completed_at = timestamp()
            receive_duration = time.perf_counter() - receive_start
            if variables is None:
                return
            if set(variables) != set(VARIABLES):
                raise RuntimeError(
                    f"Expected {list(VARIABLES)}, received {sorted(variables)}"
                )

            receive_fields = {
                "step": step,
                "variables": list(VARIABLES),
                "started_at": receive_started_at,
                "completed_at": receive_completed_at,
                "duration_seconds": receive_duration,
            }
            timing_log.record("socket.receive", **receive_fields)
            timing_log.record("socket.receive_all", **receive_fields)

            if io is None:
                shape = variables["d1"].shape
                if len(shape) != 2:
                    raise RuntimeError(f"Expected 2-D arrays, received shape {shape}")
                io = create_consumer_output(
                    output, engine, shape, append=append_output
                )

            write_called_at = timestamp()
            write_start = time.perf_counter()
            try:
                io.write_data(variables)
            except Exception as exc:
                timing_log.record(
                    "io.write",
                    step=step,
                    called_at=write_called_at,
                    duration_seconds=time.perf_counter() - write_start,
                    status="error",
                    error_type=type(exc).__name__,
                )
                raise
            timing_log.record(
                "io.write",
                step=step,
                called_at=write_called_at,
                duration_seconds=time.perf_counter() - write_start,
                status="ok",
            )
            send_ack(connection)
            summary = ", ".join(
                f"{name}={value.shape}/{value.dtype}"
                for name, value in sorted(variables.items())
            )
            print(f"Received and wrote step {step}: {summary}", flush=True)
            step += 1
    finally:
        if io is not None:
            io.close()


def main(argv=None):
    args = parse_args(sys.argv[1:] if argv is None else argv)
    connection_path = Path(args.connection_file)
    advertise_host = args.advertise_host or args.bind_host
    session_id = str(uuid.uuid4())
    public_key = load_public_key(args.public_key)
    timing_log = TimingLog(args.timing_log)
    listener = None
    connection = None
    connection_file_contents = None

    try:
        listener = create_listener(args.bind_host, args.port)
        connection_file_contents = write_connection_file(
            connection_path, advertise_host, listener, session_id, public_key
        )
        print(f"Connection info written to {connection_path}", flush=True)
        connection = accept_connection(
            listener, session_id, public_key, args.allow_ip_range
        )
        receive_steps(
            connection,
            args.output,
            args.engine,
            timing_log,
            append_output=args.append_output,
        )
        print("Producer closed the socket channel", flush=True)
    finally:
        if connection is not None:
            connection.close()
        if listener is not None:
            listener.close()
        remove_own_connection_file(connection_path, connection_file_contents)
        timing_log.close()


if __name__ == "__main__":
    main()
