#!/usr/bin/env python3
import argparse
import socket
import sys
import time
import uuid
from pathlib import Path

from connection_security import (
    load_public_key,
    remove_connection_file_if_unchanged,
    write_encrypted_connection_file,
)
from consumer_output import create_consumer_output
from socket_io import VARIABLE_PAIRS
from socket_protocol import (
    receive_hello,
    receive_message,
    verify_producer_private_key,
)
from timing_log import TimingLog, timestamp


def parse_args(argv):
    parser = argparse.ArgumentParser(
        description="Receive mockProducer arrays over three TCP connections."
    )
    parser.add_argument("connection_file", help="rendezvous file to create")
    parser.add_argument("output", help="ADIOS output, or pickle output fallback")
    parser.add_argument(
        "--public-key",
        required=True,
        help="Curve25519 public key generated by keygen.py (required)",
    )
    parser.add_argument(
        "--engine",
        default="BP5",
        help="ADIOS engine (default: BP5)",
    )
    parser.add_argument(
        "--bind-host",
        default="127.0.0.1",
        help="interface on which to listen (default: 127.0.0.1)",
    )
    parser.add_argument(
        "--advertise-host",
        help="host name written to the file (default: bind host)",
    )
    parser.add_argument(
        "--timing-log",
        default="mockConsumerSockets.log",
        help="timing log file (default: mockConsumerSockets.log)",
    )
    return parser.parse_args(argv)


def create_listener(bind_host):
    listener = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    try:
        listener.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        listener.bind((bind_host, 0))
        listener.listen(len(VARIABLE_PAIRS))
    except Exception:
        listener.close()
        raise
    return listener


def write_connection_file(path, advertise_host, listener, session_id, public_key):
    connection_info = {
        "id": "sockets",
        "consumer_id": session_id,
        "host": advertise_host,
        "port": listener.getsockname()[1],
    }
    return write_encrypted_connection_file(path, connection_info, public_key)


def remove_own_connection_file(path, expected_contents):
    remove_connection_file_if_unchanged(path, expected_contents)


def accept_connections(listener, session_id, public_key):
    by_variables = {}
    try:
        for _ in VARIABLE_PAIRS:
            connection, address = listener.accept()
            try:
                verify_producer_private_key(connection, public_key)
                pair, requested_consumer_id = receive_hello(connection)
                if requested_consumer_id != session_id:
                    raise RuntimeError(
                        "Producer used stale socket connection information"
                    )
                if pair not in VARIABLE_PAIRS:
                    raise RuntimeError(f"Unknown variable channel: {pair}")
                if pair in by_variables:
                    raise RuntimeError(f"Duplicate variable channel: {pair}")
            except Exception:
                connection.close()
                raise
            by_variables[pair] = connection
            print(
                f"Connected {'/'.join(pair)} from {address[0]}:{address[1]}",
                flush=True,
            )
    except Exception:
        for connection in by_variables.values():
            connection.close()
        raise
    return [by_variables[pair] for pair in VARIABLE_PAIRS]


def receive_steps(connections, output, engine, timing_log):
    io = None
    step = 0
    try:
        while True:
            receive_all_started_at = timestamp()
            receive_all_start = time.perf_counter()
            messages = []
            receive_records = []
            for pair, connection in zip(VARIABLE_PAIRS, connections):
                receive_started_at = timestamp()
                receive_start = time.perf_counter()
                message = receive_message(connection)
                receive_completed_at = timestamp()
                if message is not None:
                    receive_records.append(
                        {
                            "step": step,
                            "variables": list(pair),
                            "started_at": receive_started_at,
                            "completed_at": receive_completed_at,
                            "duration_seconds": time.perf_counter() - receive_start,
                        }
                    )
                messages.append(message)

            receive_all_completed_at = timestamp()
            receive_all_duration = time.perf_counter() - receive_all_start
            if all(message is None for message in messages):
                return
            if any(message is None for message in messages):
                raise RuntimeError("Socket channels ended at different times")
            for record in receive_records:
                timing_log.record("socket.receive", **record)
            timing_log.record(
                "socket.receive_all",
                step=step,
                variables=[name for pair in VARIABLE_PAIRS for name in pair],
                started_at=receive_all_started_at,
                completed_at=receive_all_completed_at,
                duration_seconds=receive_all_duration,
            )

            variables = {}
            for pair, received in zip(VARIABLE_PAIRS, messages):
                if set(received) != set(pair):
                    raise RuntimeError(
                        f"Expected {'/'.join(pair)}, received {sorted(received)}"
                    )
                variables.update(received)

            if io is None:
                shape = variables["d1"].shape
                if len(shape) != 2:
                    raise RuntimeError(f"Expected 2-D arrays, received shape {shape}")
                io = create_consumer_output(output, engine, shape)

            write_called_at = timestamp()
            write_start = time.perf_counter()
            try:
                io.write_data(variables)
            except Exception as exc:
                timing_log.record(
                    "io.write",
                    step=step,
                    called_at=write_called_at,
                    duration_seconds=time.perf_counter() - write_start,
                    status="error",
                    error_type=type(exc).__name__,
                )
                raise
            timing_log.record(
                "io.write",
                step=step,
                called_at=write_called_at,
                duration_seconds=time.perf_counter() - write_start,
                status="ok",
            )
            summary = ", ".join(
                f"{name}={value.shape}/{value.dtype}"
                for name, value in sorted(variables.items())
            )
            print(f"Received and wrote step {step}: {summary}", flush=True)
            step += 1
    finally:
        if io is not None:
            io.close()


def main(argv=None):
    args = parse_args(sys.argv[1:] if argv is None else argv)
    connection_path = Path(args.connection_file)
    advertise_host = args.advertise_host or args.bind_host
    session_id = str(uuid.uuid4())
    public_key = load_public_key(args.public_key)
    timing_log = TimingLog(args.timing_log)
    listener = None
    connections = []
    connection_file_contents = None

    try:
        listener = create_listener(args.bind_host)
        connection_file_contents = write_connection_file(
            connection_path, advertise_host, listener, session_id, public_key
        )
        print(f"Connection info written to {connection_path}", flush=True)
        connections = accept_connections(listener, session_id, public_key)
        receive_steps(connections, args.output, args.engine, timing_log)
        print("Producer closed all socket channels", flush=True)
    finally:
        for connection in connections:
            connection.close()
        if listener is not None:
            listener.close()
        remove_own_connection_file(connection_path, connection_file_contents)
        timing_log.close()


if __name__ == "__main__":
    main()
