[server]
host = pnorbert@dtn.nersc

# Default is "direct", connecting via socket directly to host.
# "ssh" will use ssh connection as defined in ~/.ssh/config
socket_transport = ssh

working_directory = /global/cfs/projectdirs/m3239/pnorbert/streamdatain/mock_data_streamer
python = ../.venv/bin/python3
script = mockConsumerSingleSocket.py

connection_file = ../data/logs/nersc-20260928.conn.json
output_directory = ../data/data/nersc-20260928
file_interval_seconds = 3600
stdout_log = ../data/logs/nersc-20260928.consumer.stdout.log
pid_file = ../data/logs/nersc-20260928.consumer.pid
timing_log = ../data/logs/nersc-20260928.consume.jsonl

public_key = ../keys/mockkey.pub
allow_ip_range = 127.0.0.1/32
port = 8501-8599
bind_host = 127.0.0.1
advertise_host = 127.0.0.1

socket_timeout_seconds = 60
startup_timeout_seconds = 60
retry_delay_seconds = 15
max_relaunch_attempts = 0

ntfy_topic_info = mock_data_streamer_nersc_info
ntfy_topic_action = mock_data_streamer_nersc_action
